config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :device_ins
  root to: "device_ins#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device_in.rb
# == Schema Information
#
# Table name: device_ins
#
#  id         :bigint           not null, primary key
#  content    :text(65535)
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class DeviceIn < ApplicationRecord
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/device_ins_controller.rb
class DeviceInsController < ApplicationController
  before_action :set_device_in, only: %i[ show edit update destroy ]

  # GET /device_ins or /device_ins.json
  def index
    @device_ins = DeviceIn.all
  end

  # GET /device_ins/1 or /device_ins/1.json
  def show
  end

  # GET /device_ins/new
  def new
    @device_in = DeviceIn.new
  end

  # GET /device_ins/1/edit
  def edit
  end

  # POST /device_ins or /device_ins.json
  def create
    @device_in = DeviceIn.new(device_in_params)

    respond_to do |format|
      if @device_in.save
        format.html { redirect_to device_in_url(@device_in), notice: "Device in was successfully created." }
        format.json { render :show, status: :created, location: @device_in }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @device_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /device_ins/1 or /device_ins/1.json
  def update
    respond_to do |format|
      if @device_in.update(device_in_params)
        format.html { redirect_to device_in_url(@device_in), notice: "Device in was successfully updated." }
        format.json { render :show, status: :ok, location: @device_in }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @device_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /device_ins/1 or /device_ins/1.json
  def destroy
    @device_in.destroy

    respond_to do |format|
      format.html { redirect_to device_ins_url, notice: "Device in was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device_in
      @device_in = DeviceIn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def device_in_params
      params.require(:device_in).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/device_ins_helper.rb
module DeviceInsHelper
end

app/views/device_ins/_form.html.erb
<%= form_with(model: device_in) do |form| %>
  <% if device_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device_in.errors.count, "error") %> prohibited this device_in from being saved:</h2>

      <ul>
        <% device_in.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/device_ins/edit.html.erb
<h1>Editing Device In</h1>

<%= render 'form', device_in: @device_in %>

<%= link_to 'Show', @device_in %> |
<%= link_to 'Back', device_ins_path %>

app/views/device_ins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Device Ins</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @device_ins.each do |device_in| %>
      <tr>
        <td><%= device_in.title %></td>
        <td><%= device_in.content %></td>
        <td><%= link_to 'Show', device_in %></td>
        <td><%= link_to 'Edit', edit_device_in_path(device_in) %></td>
        <td><%= link_to 'Destroy', device_in, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device In', new_device_in_path %>

app/views/device_ins/new.html.erb
<h1>New Device In</h1>

<%= render 'form', device_in: @device_in %>

<%= link_to 'Back', device_ins_path %>

app/views/device_ins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @device_in.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @device_in.content %>
</p>

<%= link_to 'Edit', edit_device_in_path(@device_in) %> |
<%= link_to 'Back', device_ins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviceIns</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if user_signed_in? %>
        <%= link_to 'プロフィール変更', edit_user_registration_path %>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'サインアップ', new_user_registration_path %>
        <%= link_to 'ログイン', new_user_session_path %>
      <% end %>
    </nav>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>